[[plugins]]
repo = 'Shougo/dein.vim'

# 補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_ignore_case = 1
    let g:deoplete#enable_smart_case = 1
'''

hook_post_source = '''
    let g:deoplete#sources = {}
    let g:deoplete#sources._ = ['buffer', 'member', 'tag', 'file', 'dictionary', 'neosnippet', 'ruby']
    let g:deoplete#ignore_sources = {
        \ '_': ['omni']
        \ }
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

# 非同期処理全般
[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_source = ['tyru/open-browser-github.vim']

[[plugins]]
repo = 'tyru/open-browser-github.vim'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']
depends = ['ryanoasis/vim-devicons']
depends = ['tpope/vim-fugitive']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tpope/vim-fugitive'
